# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: chekout code
        uses: actions/checkout@v3
          
  ## Trufflehog secret scan        
  trufflehog_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: chekout code
        uses: actions/checkout@v3
       
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
  
  ## PHP SAST SCAN      
  sast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: chekout code
        uses: actions/checkout@v3
        
      - name: Security Scanner for PHP
        uses: psalm/psalm-github-security-scan@1.2.1
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
        
        
  ## PHP SAST SCAN      
  ZAP_scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        #uses: zaproxy/action-full-scan@v0.4.0
        with:
          #token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://35.89.117.245:8081/'
          #rules_file_name: '.zap/rules.tsv'
          #cmd_options: '-a -j'
        
      
        
      # Runs a single command using the runners shell
      #- name: Run a one-line script
       # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: |
        #  echo Add other actions to build,
         # echo test, and deploy your project.
